### ISSUE TITLE
[Bug] Duplicate issues are generated for a binary application

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/tackle2-addon-analyzer#108]
Affected Version: 0.5.0-beta.1

Binary used: https://github.com/windup/windup-sample-apps/blob/master/sample-binaries/jee-example-app-1.0.0.ear

Run analysis with Source + Dependencies mode, Application and Internal Deps scope with targets EAP and Containerization. A rule is matched twice:

**log4j-removed-00001**

![image](https://github.com/konveyor/tackle2-addon-analyzer/assets/9839757/57320503-1390-4546-9c82-3d2bff332590)

**Comment by dymurray** [comment]
Closing, these are different rules.
