### ISSUE TITLE
:bug: Analyzer and addon not using the same m2.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-addon-analyzer#46]
The addon is using maven to fetch artifacts for mode=binary using /cache/m2 for the local repository.
The analyzer is using the default ${HOME}/.m2 which is not mapped to the /cache/m2 with is shared when RWX is supported.

May require: https://github.com/konveyor/analyzer-lsp/issues/338

**Comment by shawn-hurley** [comment]
After looking at this in the analyzer, if a man settings file is passed we will use that settings file correctly. 

I think we should add `<localRepository>` to the settings file when the cache/m2 is available.

**Comment by shawn-hurley** [comment]
I am going to need some serious help finding out how to make this code change in the project. Could we set up some time to help me walk through this

**Comment by shawn-hurley** [comment]
fiexed by #57
