### ISSUE TITLE
:sparkles: Build and pass label selector.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-addon-analyzer#6]
Build and pass label selector using source and target labels.

Seems the target labels are OR(ed) together but not sure what to do with source labels.

Example:
- konveyor.io/source=oraclejdk
- konveyor.io/target=openjdk
- konveyor.io/target=openjdk

I suspect the source and target needs to be grouped?

Like: 
```
(konveyor.io/source=oraclejdk && konveyor.io/target=openjdk) || konveyor.io/target=openjdk

**Comment by pranavgaikwad** [comment]
@jortel We do not need to group targets / sources. Following general format should work

```
(target1 || target2 ... || targetN ) && (source1 || source2 ... || sourceN)
``` 

This is because its rare to have a Rule that has unrelated source and target labels on them, if there is any, it should be a mistake and we should fix that.

**Comment by jortel** [comment]
Rule A:
 - labels
   - source=S1
   - target=T1
 
Rule B:
 - labels
   - target=T1

Selector of (source=S1 && target=T1) will only match rule A?
