### ISSUE TITLE
Analysis logs should be available for debugging

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/tackle2-addon-analyzer#61]
It is hard to debug issues without having access to full analysis logs. It'd be great if analysis logs could be stored somewhere, I don't know the right answer where, but there seems to be a need of being able to look at full analysis logs.

**Comment by jortel** [comment]
### Solution ###
Add new checkbox to the analysis advanced options page:
```
[ ] Enable enhanced analysis details.
```
When enabled:
1. Passes Verbosity=1 to the addon.
2. The addon enables capture of output for the analyzer-lsp and analyzer-dep commands.
3. A `File` is created in the hub and attached to the TaskReport.
4. Output is appended to the file (uploaded as it's output by the command) to the hub.  This is rate limited <= 1 second using a auto-adjusted backoff.
5. Short term: the files will be injected to the Task.Activity by the GET /tasks endpoint.

Long term: The files can be listed, viewed and downloaded on a new Tab on the "Analysis Detail" modal.

**Comment by jortel** [comment]
Closed: #68
